import { devuiDarkTheme, devuiLightTheme, Theme } from '../theme';
export const infinityTheme: Theme = new Theme({
  id: 'infinity-theme',
  name: '无限主题',
  data: {
    ...devuiLightTheme.data,
    'b-brand-foil': '#F2F2F3',
    'b-global-bg': '#F8F8FA',
    'b-base-bg': '#ffffff',
    'b-text': '#252B3A',
    'b-aide-text': '#71757f',
    'b-placeholder': '#babbc0',
    'b-disabled-text': '#cfd0d3',
    'b-disabled-bg': '#f5f5f5',
    'b-line': '#D7D8DA',
    'b-dividing-line': '#F2F2F3',
    'b-area': '#f5f5f5',
    'b-list-item-hover-bg': '#F2F2F3',
    'b-list-item-active-bg': '#F2F5FC',
    'b-list-item-active-hover-bg': '#F2F5FC',
    'b-list-item-selected-bg': '#F2F5FC',
    'b-list-item-hover-text': '#252b3a',
    'b-list-item-active-text': '#252B3A',
    'b-form-control-line-hover': '#9b9fa8',
    'b-form-control-line': '#D7D8DA',
    'b-form-control-bg': '#ffffff',
    'b-icon-text': '#71757f',
    'b-icon-fill': '#71757f',
    'b-icon-fill-weak': '#babbc0',
    'b-icon-fill-hover': '#252b3a',
    'b-icon-fill-active': '#252b3a',
    'b-icon-fill-active-hover': '#252b3a',
    'b-label-bg': '#E9EDFA',
    'b-border-radius': '4px',
    'b-font-size': '14px',
    'b-font-size-md': '14px',
    'b-font-size-card-title': '16px',
    'b-shadow-length-fullscreen-overlay': '0 0 6px 0',
    'b-border-radius-card': '8px',
    'b-border-radius-full': '100px',
    'b-waiting': '#beccfa',
    'b-danger-bg': '#ffd5d4',
    'b-shape-icon-fill': '#d7d8da',
    'b-shape-icon-fill-hover': '#babbc0',
    'b-shape-icon-fill-active': '#babbc0',
    'b-shape-icon-fill-disabled': '#f5f5f5',
    'b-btn-padding': '0 16px',
    'b-btn-common-bg': '#ebebeb',
    'b-btn-common-bg-hover': '#d1d1d1',
    'b-btn-common-bg-active': '#bdbdbd',
    'b-btn-common-color-hover': '#252b3a',
    'b-btn-common-color-active': '#252b3a',
    'b-btn-common-border-color': 'transparent',
    'b-btn-common-border-color-hover': 'transparent',
    'b-btn-common-border-color-active': 'transparent',
    'b-btn-sm-padding': '0 12px',
    'b-btn-lg-padding': '0 20px',
  },
  extends: 'devui-light-theme',
  isDark: false,
});

export const provenceTheme: Theme = new Theme({
  id: 'provence-theme',
  name: '紫罗兰主题',
  data: {
    ...infinityTheme.data,
    'b-brand': '#7B69EE',
    'b-brand-foil': '#F5F5F9',
    'b-brand-active-focus': '#7B69EE',
    'b-primary-active': '#7B69EE',
    'b-brand-hover': '#7B69EE',
    'b-global-bg': '#f9fafb',
    'b-base-bg': '#ffffff',
    'b-text': '#070036',
    'b-aide-text': '#717087',
    'b-placeholder': '#babbc0',
    'b-disabled-text': '#cfd0d3',
    'b-disabled-bg': '#f5f5f6',
    'b-line': '#E2E2E5',
    'b-dividing-line': '#F2F2F3',
    'b-list-item-hover-bg': '#F5F5F9',
    'b-list-item-active-bg': '#7B69EE',
    'b-list-item-active-hover-bg': '#7B69EE',
    'b-list-item-selected-bg': '#F4F2FF',
    'b-list-item-hover-text': '#252b3a',
    'b-list-item-active-text': '#ffffff',
    'b-form-control-line-hover': '#A3A6AC',
    'b-form-control-line': '#D7D8DA',
    'b-icon-text': '#babbc0',
    'b-brand-active': '#7B69EE',
    'b-primary': '#7B69EE',
    'b-primary-hover': '#7B69EE',
    'b-form-control-line-active': '#7B69EE',
    'b-form-control-line-active-hover': '#7B69EE',
    'b-icon-fill-active': '#7B69EE',
    'b-icon-fill-active-hover': '#7B69EE',
    'b-label-bg': '#F4F2FF',
    'b-embed-search-bg': '#F4F2FF',
    'b-connected-overlay-line': '#7B69EE',
    'b-primary-disabled': '#d8d2fa',
    'b-icon-fill-active-disabled': '#d8d2fa',
  },
  extends: 'infinity-theme',
  isDark: false,
});

export const sweetTheme: Theme = new Theme({
  id: 'sweet-theme',
  name: '蜜糖主题',
  data: {
    ...infinityTheme.data,
    'b-brand': '#ec66ab',
    'b-brand-foil': '#f8f1f5',
    'b-brand-active-focus': '#ec66ab',
    'b-primary-active': '#ec66ab',
    'b-brand-hover': '#ec66ab',
    'b-global-bg': '#f9fafb',
    'b-base-bg': '#ffffff',
    'b-text': '#2f272f',
    'b-aide-text': '#827d82',
    'b-placeholder': '#bdb8bd',
    'b-disabled-text': '#cbcacb',
    'b-disabled-bg': '#f6f6f6',
    'b-line': '#aea6ad',
    'b-dividing-line': '#eae7e9',
    'b-list-item-hover-bg': '#f8f1f5',
    'b-list-item-active-bg': '#ffdcee',
    'b-list-item-active-hover-bg': '#ffdcee',
    'b-list-item-selected-bg': '#ffdcee',
    'b-list-item-hover-text': '#252b3a',
    'b-list-item-active-text': '#252b3a',
    'b-form-control-line-hover': '#A3A6AC',
    'b-form-control-line': '#D7D8DA',
    'b-icon-text': '#babbc0',
    'b-brand-active': '#ec66ab',
    'b-primary': '#ec66ab',
    'b-primary-hover': '#ec66ab',
    'b-form-control-line-active': '#ec66ab',
    'b-form-control-line-active-hover': '#ec66ab',
    'b-icon-fill-active': '#ec66ab',
    'b-icon-fill-active-hover': '#ec66ab',
    'b-label-bg': '#ffdcee',
    'b-embed-search-bg': '#ffdcee',
    'b-connected-overlay-line': '#ec66ab',
    'b-primary-disabled': '#fad1e6',
    'b-icon-fill-active-disabled': '#fad1e6',
  },
  extends: 'infinity-theme',
  isDark: false,
});

export const deepTheme: Theme = new Theme({
  id: 'deep-theme',
  name: '深邃夜空主题',
  data: {
    ...infinityTheme.data,
    'b-brand': '#252b3a',
    'b-brand-foil': '#f3f4f7',
    'b-brand-active-focus': '#252b3a',
    'b-primary-active': '#252b3a',
    'b-brand-active': '#252b3a',
    'b-brand-hover': '#252b3a',
    'b-global-bg': '#f7f8fa',
    'b-base-bg': '#ffffff',
    'b-text': '#252b3a',
    'b-aide-text': '#505c7c',
    'b-placeholder': '#9ba6bf',
    'b-disabled-text': '#a8b1c7',
    'b-disabled-bg': '#f7f8fa',
    'b-line': '#cdd2df',
    'b-dividing-line': '#e6e9ef',
    'b-list-item-hover-bg': '#f3f4f7',
    'b-list-item-active-bg': '#252b3a',
    'b-list-item-active-hover-bg': '#252b3a',
    'b-list-item-selected-bg': '#252b3a',
    'b-list-item-hover-text': '#252b3a',
    'b-list-item-active-text': '#ffffff',
    'b-form-control-line-hover': '#A3A6AC',
    'b-form-control-line': '#D7D8DA',
    'b-icon-text': '#babbc0',
    'b-primary': '#252b3a',
    'b-primary-hover': '#252b3a',
    'b-form-control-line-active': '#252b3a',
    'b-form-control-line-active-hover': '#252b3a',
    'b-icon-fill-active': '#252b3a',
    'b-icon-fill-active-hover': '#252b3a',
    'b-connected-overlay-line': '#252b3a',
    'b-primary-disabled': '#bebfc4',
    'b-icon-fill-active-disabled': '#bebfc4',
  },
  extends: 'infinity-theme',
  isDark: false,
});

export const galaxyTheme: Theme = new Theme({
  id: 'galaxy-theme',
  name: '追光主题',
  data: {
    ...devuiDarkTheme.data,
    'b-brand-foil': '#F2F2F3',
    'b-global-bg': '#000000',
    'b-base-bg': '#1F1F1F',
    'b-text': '#F5F5F5',
    'b-aide-text': '#A3A3A3',
    'b-placeholder': '#616161',
    'b-disabled-text': '#838383',
    'b-disabled-bg': '#3F3F3F',
    'b-line': '#565656',
    'b-dividing-line': '#303030',
    'b-list-item-hover-bg': '#313131',
    'b-list-item-active-bg': '#30333D',
    'b-list-item-active-hover-bg': '#30333D',
    'b-list-item-selected-bg': '#30333D',
    'b-list-item-hover-text': '#F5F5F5',
    'b-list-item-active-text': '#526ECC',
    'b-primary-disabled': '#3f3f3f',
    'b-form-control-bg': '#292a2e',
    'b-form-control-line': '#565656',
    'b-icon-text': '#A3A3A3',
    'b-connected-overlay-bg': '#282828',
    'b-fullscreen-overlay-bg': '#282828',
    'b-warning-line': '#a2622a',
    'b-warning-bg': '#4b2e14',
    'b-success-line': '#27846b ',
    'b-success-bg': '#123d32',
    'b-danger-line': '#9f4844',
    'b-danger-bg': '#4a2120',
    'b-info-line': '#3c5091',
    'b-info-bg': '#1c2543',
    'b-default-bg': '#313131',
    'b-border-radius': '4px',
    'b-font-size': '14px',
    'b-font-size-md': '14px',
    'b-font-size-card-title': '16px',
    'b-shadow-length-fullscreen-overlay': '0 0 6px 0',
    'b-border-radius-card': '4px',
  },
  extends: 'devui-dark-theme',
  isDark: true,
});
