import { Theme } from './theme';
export const devuiLightTheme: Theme = new Theme({
  id: 'b-light-theme',
  name: 'Light Mode',
  data: {
    // 基础变量
    'b-global-bg': '#f3f6f8',
    'b-global-bg-normal': '#ffffff',
    'b-base-bg': '#ffffff',
    'b-base-bg-dark': '#333854',
    'b-brand': '#5e7ce0',
    'b-brand-foil': '#859bff',
    'b-brand-hover': '#7693f5',
    'b-brand-active': '#526ecc',
    'b-brand-active-focus': '#344899',
    'b-contrast': '#c7000b',
    'b-text': '#252b3a',
    'b-text-weak': '#575d6c',
    'b-aide-text': '#8a8e99',
    'b-aide-text-stress': '#575d6c',
    'b-placeholder': '#8a8e99',
    'b-light-text': '#ffffff',
    'b-dark-text': '#252b3a',
    'b-link': '#526ecc',
    'b-link-active': '#526ecc',
    'b-link-light': '#96adfa',
    'b-link-light-active': '#beccfa',
    'b-line': '#adb0b8',
    'b-dividing-line': '#dfe1e6',
    'b-block': '#ffffff',
    'b-area': '#f8f8f8',
    'b-danger': '#f66f6a',
    'b-warning': '#fac20a',
    'b-waiting': '#9faad7',
    'b-success': '#50d4ab',
    'b-info': '#5e7ce0',
    'b-initial': '#e9edfa',
    'b-unavailable': '#f5f5f6',
    'b-shadow': 'rgba(37, 43, 58, 0.2)',
    'b-light-shadow': 'rgba(37, 43, 58, 0.1)',
    // 图标
    'b-icon-text': '#252b3a',
    'b-icon-bg': '#ffffff',
    'b-icon-fill': '#71757f',
    'b-icon-fill-hover': '#252b3a',
    'b-icon-fill-active': '#252b3a',
    'b-icon-fill-active-hover': '#526ecc',
    // 表单
    'b-form-control-line': '#adb0b8',
    'b-form-control-line-hover': '#575d6c',
    'b-form-control-line-active': '#5e7ce0',
    'b-form-control-line-active-hover': '#344899',
    'b-list-item-active-bg': '#5e7ce0',
    'b-list-item-active-text': '#ffffff',
    'b-list-item-active-hover-bg': '#526ecc',
    'b-list-item-hover-bg': '#f2f5fc',
    'b-list-item-hover-text': '#526ecc',
    'b-list-item-selected-bg': '#e9edfa',
    'b-list-item-strip-bg': '#f2f5fc',
    // 禁用
    'b-disabled-bg': '#f5f5f6',
    'b-disabled-line': '#dfe1e6',
    'b-disabled-text': '#adb0b8',
    'b-primary-disabled': '#beccfa',
    'b-icon-fill-active-disabled': '#beccfa',
    // 特殊背景色
    'b-label-bg': '#eef0f5',
    'b-connected-overlay-bg': '#ffffff',
    'b-connected-overlay-line': '#526ecc',
    'b-fullscreen-overlay-bg': '#ffffff',
    'b-feedback-overlay-bg': '#464d6e',
    'b-feedback-overlay-text': '#dfe1e6',
    'b-embed-search-bg': '#f2f5fc',
    'b-embed-search-bg-hover': '#eef0f5',
    'b-float-block-shadow': 'rgba(94, 124, 224, 0.3)',
    'b-highlight-overlay': 'rgba(255, 255, 255, 0.8)',
    'b-range-item-hover-bg': '#e9edfa',
    // 按钮
    'b-primary': '#5e7ce0',
    'b-primary-hover': '#7693f5',
    'b-primary-active': '#344899',
    'b-contrast-hover': '#d64a52',
    'b-contrast-active': '#b12220',
    // 状态
    'b-danger-line': '#f66f6a',
    'b-danger-bg': '#ffeeed',
    'b-warning-line': '#fa9841',
    'b-warning-bg': '#fff3e8',
    'b-info-line': '#5e7ce0',
    'b-info-bg': '#f2f5fc',
    'b-success-line': '#50d4ab',
    'b-success-bg': '#edfff9',
    'b-primary-line': '#5e7ce0',
    'b-primary-bg': '#f2f5fc',
    'b-default-line': '#5e7ce0',
    'b-default-bg': '#f3f6f8',
    // 字体设置相关
    'b-font-size': '12px',
    'b-font-size-card-title': '14px',
    'b-font-size-page-title': '16px',
    'b-font-size-modal-title': '18px',
    'b-font-size-price': '20px',
    'b-font-size-data-overview': '24px',
    'b-font-size-icon': '16px',
    'b-font-size-sm': '12px',
    'b-font-size-md': '12px',
    'b-font-size-lg': '14px',
    'b-font-title-weight': 'bold',
    'b-font-content-weight': 'normal',
    'b-line-height-base': '1.5',
    // 圆角
    'b-border-radius': '2px',
    'b-border-radius-feedback': '4px',
    'b-border-radius-card': '6px',
    // 阴影
    'b-shadow-length-base': '0 1px 4px 0',
    'b-shadow-length-slide-left': '-2px 0 8px 0',
    'b-shadow-length-slide-right': '2px 0 8px 0',
    'b-shadow-length-connected-overlay': '0 2px 8px 0',
    'b-shadow-length-hover': '0 4px 16px 0',
    'b-shadow-length-feedback-overlay': '0 4px 16px 0',
    'b-shadow-fullscreen-overlay': '0 8px 40px 0',
    // 动效
    'b-animation-duration-slow': '300ms',
    'b-animation-duration-base': '200ms',
    'b-animation-duration-fast': '100ms',
    'b-animation-ease-in': 'cubic-bezier(0.5, 0, 0.84, 0.25)',
    'b-animation-ease-out': 'cubic-bezier(0.16, 0.75, 0.5, 1)',
    'b-animation-ease-in-out': 'cubic-bezier(0.5, 0.05, 0.5, 0.95)',
    'b-animation-ease-in-out-smooth': 'cubic-bezier(0.645, 0.045, 0.355, 1)',
    'b-animation-linear': 'cubic-bezier(0, 0, 1, 1)',
    // zIndex
    'b-z-index-full-page-overlay': '1080',
    'b-z-index-pop-up': '1060',
    'b-z-index-dropdown': '1052',
    'b-z-index-modal': '1050',
    'b-z-index-drawer': '1040',
    'b-z-index-framework': '1000',

    // Menu
    'b-menu-item': '#252b3a',
    'b-menu-item-sub': '#6C6C6C',
    'b-menu-item-hover': '#0f0f0f',
    'b-menu-disabled': '#919191',
  },
  isDark: false,
});
export const devuiGreenTheme: Theme = new Theme({
  id: 'b-green-theme',
  name: 'Green - Light Mode',
  data: {
    ...devuiLightTheme.data,
    'b-global-bg': '#f3f8f7',
    'b-brand': '#3DCCA6',
    'b-brand-foil': '#7fdac1',
    'b-brand-hover': '#6DDEBB',
    'b-brand-active': '#07c693',
    'b-brand-active-focus': '#369676',
    'b-link': '#07c693',
    'b-link-active': '#07c693',
    'b-link-light': '#96fac8',
    'b-link-light-active': '#befade',
    'b-info': '#079CCD',
    'b-initial': '#CCCCCC',
    'b-icon-fill-active': '#3DCCA6',
    'b-icon-fill-active-hover': '#07c693',
    'b-form-control-line-active': '#3DCCA6',
    'b-form-control-line-active-hover': '#2EB28A',
    'b-list-item-active-bg': '#3DCCA6',
    'b-list-item-active-hover-bg': '#07c693',
    'b-list-item-hover-bg': '#f3fef9',
    'b-list-item-hover-text': '#07c693',
    'b-list-item-selected-bg': '#f3fef9',
    'b-list-item-strip-bg': '#f3fef9',
    'b-connected-overlay-line': '#07c693',
    'b-embed-search-bg': '#f3fef9',
    'b-float-block-shadow': 'rgba(94, 224, 181, 0.3)',
    'b-primary': '#3DCCA6',
    'b-primary-hover': '#6DDEBB',
    'b-primary-active': '#369676',
    'b-info-line': '#0486b1',
    'b-info-bg': '#e3f0f5',
    'b-success-line': '#50d492',
    'b-success-bg': '#edfff9',
    'b-primary-line': '#3DCCA6',
    'b-primary-bg': '#f3fef9',
    'b-default-line': '#3DCCA6',
    'b-default-bg': '#f3f8f7',
    'b-primary-disabled': '#c5f0e5',
    'b-icon-fill-active-disabled': '#c5f0e5',
    'b-range-item-hover-bg': '#d8f9ea',
  },
  extends: 'b-light-theme',
  isDark: false,
});
export const devuiDarkTheme: Theme = new Theme({
  id: 'b-dark-theme',
  name: 'Dark Mode',
  data: {
    'b-global-bg': '#202124',
    'b-global-bg-normal': '#202124',
    'b-base-bg': '#2E2F31',
    'b-base-bg-dark': '#2e2f31',
    'b-brand': '#5e7ce0',
    'b-brand-foil': '#313a61',
    'b-brand-hover': '#425288',
    'b-brand-active': '#526ecc',
    'b-brand-active-focus': '#344899',
    'b-contrast': '#C7000B',
    'b-text': '#E8E8E8',
    'b-text-weak': '#A0A0A0',
    'b-aide-text': '#909090',
    'b-aide-text-stress': '#A0A0A0',
    'b-placeholder': '#8A8A8A',
    'b-light-text': '#ffffff',
    'b-dark-text': '#252b3a',
    'b-link': '#526ECC',
    'b-link-active': '#344899',
    'b-link-light': '#96adfa',
    'b-link-light-active': '#beccfa',
    'b-line': '#505153',
    'b-dividing-line': '#3D3E40',
    'b-block': '#606061',
    'b-area': '#34363A',
    'b-danger': '#f66f6a',
    'b-warning': '#fac20a',
    'b-waiting': '#5e6580',
    'b-success': '#50d4ab',
    'b-info': '#5e7ce0',
    'b-initial': '#64676e',
    'b-unavailable': '#5b5b5c',
    'b-shadow': 'rgba(17, 18, 19, 0.4)',
    'b-light-shadow': 'rgba(17, 18, 19, 0.5)',
    // 图标
    'b-icon-text': '#E8E8E8',
    'b-icon-bg': '#2E2F31',
    'b-icon-fill': '#606061',
    'b-icon-fill-hover': '#73788a',
    'b-icon-fill-active': '#5e7ce0',
    'b-icon-fill-active-hover': '#526ecc',
    // 表单
    'b-form-control-line': '#505153',
    'b-form-control-line-hover': '#909090',
    'b-form-control-line-active': '#5e7ce0',
    'b-form-control-line-active-hover': '#344899',
    'b-list-item-active-bg': '#5e7ce0',
    'b-list-item-active-text': '#ffffff',
    'b-list-item-active-hover-bg': '#526ecc',
    'b-list-item-hover-bg': '#383838',
    'b-list-item-hover-text': '#526ecc',
    'b-list-item-selected-bg': '#454545',
    'b-list-item-strip-bg': '#383838',
    // 禁用
    'b-disabled-bg': '#3D3E44',
    'b-disabled-line': '#505153',
    'b-disabled-text': '#7D7D7D',
    'b-primary-disabled': '#2B3458',
    'b-icon-fill-active-disabled': '#2B3458',
    // 特殊背景色
    'b-label-bg': '#46443F',
    'b-connected-overlay-bg': '#2F2F2F',
    'b-connected-overlay-line': '#526ecc',
    'b-fullscreen-overlay-bg': '#2E2F31',
    'b-feedback-overlay-bg': '#4C4C4C',
    'b-feedback-overlay-text': '#DFE1E6',
    'b-embed-search-bg': '#383838',
    'b-embed-search-bg-hover': '#3D3E40',
    'b-float-block-shadow': 'rgba(94, 124, 224, 0.3)',
    'b-highlight-overlay': 'rgba(255, 255, 255, 0.1)',
    'b-range-item-hover-bg': '#454545',
    // 按钮
    'b-primary': '#5e7ce0',
    'b-primary-hover': '#425288',
    'b-primary-active': '#344899',
    'b-contrast-hover': '#D64A52',
    'b-contrast-active': '#B12220',
    // 状态
    'b-danger-line': '#985C5A',
    'b-danger-bg': '#4B3A39',
    'b-warning-line': '#8D6138',
    'b-warning-bg': '#554434',
    'b-info-line': '#546BB7',
    'b-info-bg': '#383D4F',
    'b-success-line': '#5D887D',
    'b-success-bg': '#304642',
    'b-primary-line': '#546BB7',
    'b-primary-bg': '#383D4F',
    'b-default-line': '#5e7ce0',
    'b-default-bg': '#383838',

    // Menu
    'b-menu-item': '#dcdcdc',
    'b-menu-item-sub': '#c6c6c6',
    'b-menu-item-hover': '#fff',
    'b-menu-disabled': '#919191',
  },
  extends: 'b-light-theme',
  isDark: true,
});
export const devuiGreenDarkTheme: Theme = new Theme({
  id: 'b-green-dark-theme',
  name: 'Green - Dark Mode',
  data: {
    ...devuiDarkTheme.data,
    'b-brand': '#3DCCA6',
    'b-brand-foil': '#395e54',
    'b-brand-hover': '#4c9780',
    'b-brand-active': '#07c693',
    'b-brand-active-focus': '#297058',
    'b-link': '#07c693',
    'b-link-active': '#08a57b',
    'b-info': '#046788',
    'b-initial': '#64676e',
    'b-icon-fill-active': '#3DCCA6',
    'b-icon-fill-active-hover': '#07c693',
    'b-form-control-line-active': '#3DCCA6',
    'b-form-control-line-active-hover': '#297058',
    'b-list-item-active-bg': '#3DCCA6',
    'b-list-item-active-hover-bg': '#07c693',
    'b-list-item-hover-text': '#07c693',
    'b-connected-overlay-line': '#07c693',
    'b-embed-search-bg': '#3f4241',
    'b-float-block-shadow': 'rgba(94, 224, 181, 0.3)',
    'b-primary': '#3DCCA6',
    'b-primary-hover': '#6DDEBB',
    'b-primary-active': '#369676',
    'b-info-line': '#035e7c',
    'b-info-bg': '#383c3d',
    'b-primary-line': '#3DCCA6',
    'b-primary-bg': '#3f4241',
    'b-default-line': '#3DCCA6',
    'b-default-bg': '#383838',
    'b-primary-disabled': '#28544B',
    'b-icon-fill-active-disabled': '#28544B',
  },
  extends: 'b-dark-theme',
  isDark: true,
});
